apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: boriscernak/ambulance-wl-webapi
  newName: boriscernak/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20240422.0815 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
- name: boriscernak/ambulance-ufe
  newName: boriscernak/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20240422.0920 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
